---
title: "bognu_analysis"
output: html_document
date: "2024-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## loading packages & data
```{r}
pacman::p_load(tidyverse, ordinal, lmerTest, car, interactions)

raw <- read_tsv("data_w_themes.csv")

```


## cleaning data
```{r}
# grouping media types
raw <- raw %>% 
  mutate(media_type_name = ifelse(media_type_name == 'Regional avis', 'Avis', 
                                  ifelse(media_type_name == 'Onlinemedie uden citat', 'Blog', paste0(media_type_name)))
         )

# find media names with 3 or more reviews
media_name_count <- raw %>% 
  filter(media_type_name == 'Blog' | media_type_name == 'Avis') %>% 
  group_by(media_name) %>% 
  summarise(n = n()) %>% 
  filter(n > 2)

# select relevant columns, retain only blogs and newspapers, and medias with more than 3 reviews, then remove NAs
df <- raw %>% 
  select(title_id, rev_gender_updated, author_gender, media_name, media_type_name, author_entity_ids_c, grades) %>% 
  filter(media_type_name == 'Blog' | media_type_name == 'Avis') %>% 
  filter(media_name %in% media_name_count$media_name) %>% 
  mutate(grades_factor = as.factor(grades),
         rev_gender_updated = str_to_title(rev_gender_updated),
         author_gender = str_to_title(author_gender)) %>% 
  drop_na()
```


# Reviewer & author gender analysis

## Ordinal control analysis, cumulative linear mixed effects model
```{r}
df <- df %>% 
  mutate(grades_factor = as.factor(grades))

m0 <- ordinal::clmm(grades_factor ~ 1 + (1 | media_name) + (1| author_entity_ids_c )+ (1 |  title_id), data = df)

m1 <- ordinal::clmm(grades_factor ~ media_type_name 
                    + (1 | media_name) + (1| author_entity_ids_c )+ (1 |  title_id), data = df)
m2 <- ordinal::clmm(grades_factor ~ media_type_name + rev_gender_updated + (1 | media_name) 
                    + (1| author_entity_ids_c ) + (1 | title_id), data = df)
m3 <- ordinal::clmm(grades_factor ~ media_type_name + rev_gender_updated + author_gender 
                    + (1 | media_name) + (1| author_entity_ids_c ) + (1 | title_id), data = df)
m4 <- ordinal::clmm(grades_factor ~ media_type_name + rev_gender_updated + author_gender + rev_gender_updated:author_gender 
                    + (1 | media_name) + (1| author_entity_ids_c ) + (1 |title_id), data = df)

anova(m0, m1, m2, m3, m4)

```

```{r}
summary(m4)

palette <- c("#AEC5EB", "#904E55", "#243010")

ggplot(df, aes(x = grades,  group = author_gender))+
  geom_bar(aes(y = after_stat(prop), fill = author_gender), position = 'dodge', stat = 'count', color = 'black')+
  geom_text(aes(label = scales::percent(after_stat(prop), accuracy = 0.1),
                y = after_stat(prop)),
            stat = 'count',
            size = 3,
            vjust = -0.3,
            position = position_dodge(1))+
  facet_grid(media_type_name~rev_gender_updated)+
  scale_fill_manual(values = palette)+
  theme_bw()+
  xlab('Rating')+
  ylab('Proportion, grouped by author gender')+
  labs(fill = 'Author Gender')+
  scale_y_continuous(sec.axis = sec_axis(~ . , name = "Media Type", breaks = NULL, labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Reviewer Gender", breaks = NULL, labels = NULL))


ggsave('proportion_grades_gender.png', height = 3000, width = 4500, units = 'px', dpi = 'print')
```

## Main analysis - linear mixed effects models 
```{r}

lm0 <- lmerTest::lmer(grades ~ 1 + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = df)
lm1 <- lmerTest::lmer(grades ~ media_type_name  
                      + (1 | media_name)+ (1 | author_entity_ids_c / title_id), data = df)
lm2 <- lmerTest::lmer(grades ~ media_type_name + rev_gender_updated  
                      + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = df)
lm3 <- lmerTest::lmer(grades ~ media_type_name + rev_gender_updated + author_gender 
                      + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = df)
lm4 <- lmerTest::lmer(grades ~ media_type_name + rev_gender_updated + author_gender + rev_gender_updated:author_gender
                     + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = df)

anova(lm0, lm1, lm2, lm3, lm4)
```


```{r}
vif(lm4)

summary(lm4)


cat_plot(model = lm4, pred = rev_gender_updated, modx = author_gender, 
         geom = 'line', interval.geom = 'linerange', x.label = 'Reviewer Gender', y.label = 'Mean Rating',
         legend.main = 'Author Gender', colors = palette)

ggsave('gender_model_results.png', height = 3000, width = 4500, units = 'px', dpi = 'print')


```


```{r}
# make pretty plot
df <- df %>% 
  mutate(rev_gender_dummy = ifelse(rev_gender_updated == 'female', 0, 1))


lm4 <- lmerTest::lmer(grades ~ media_type_name + rev_gender_dummy + author_gender + rev_gender_dummy:author_gender
                     + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = df)

interact_plot(model = lm4, pred = rev_gender_dummy, modx = author_gender, interval = T, 
              x.label = 'Reviewer Gender', y.label = 'Mean Rating', legend.main = 'Author Gender', colors = palette)
```

# Genre analysis
```{r}
# clean data 
df <- raw %>% 
  select(title_id, rev_gender_updated, author_gender, 
         media_name, media_type_name, author_entity_ids_c, 
         grades, category) %>% 
  filter(media_type_name == 'Blog' | media_type_name == 'Avis') %>% 
  filter(media_name %in% media_name_count$media_name) %>% 
  mutate(grades_factor = as.factor(grades)) %>% 
  drop_na()

# select interesting genres
category_subset <- df %>% 
  filter(category %in% c('Romantisk skønlitteratur', 'Internationale klassikere', 'Skønlitteratur: generelt'))

# reorder so fiction, general becomes baseline
category_subset$category <- factor(category_subset$category, levels=c('Skønlitteratur: generelt', 'Internationale klassikere', 'Romantisk skønlitteratur'))

```


## Ordinal control analysis
```{r}

m0 <- ordinal::clmm(grades_factor ~ 1 + (1 | media_name) + (1| author_entity_ids_c )+ (1 | title_id), data = category_subset)

m1 <- ordinal::clmm(grades_factor ~ media_type_name 
                    + (1 | media_name) + (1| author_entity_ids_c )+ (1 | title_id), data = category_subset)
m2 <- ordinal::clmm(grades_factor ~ media_type_name + rev_gender_updated 
                    + (1 | media_name) + (1| author_entity_ids_c )+ (1 | title_id), data = category_subset)
m3 <- ordinal::clmm(grades_factor ~ media_type_name + rev_gender_updated + category 
                    + (1 | media_name) +  (1| author_entity_ids_c ) + (1 | title_id), data = category_subset)
m4 <- ordinal::clmm(grades_factor ~ media_type_name + rev_gender_updated + category + rev_gender_updated:category
                    + (1 | media_name) + (1| author_entity_ids_c ) + (1 |title_id), data = category_subset)

anova(m0, m1, m2, m3, m4)


```

## Main analysis
```{r}
lm0 <- lmerTest::lmer(grades ~ 1 + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = category_subset)

lm1 <- lmerTest::lmer(grades ~ media_type_name 
                    + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = category_subset)
lm2 <- lmerTest::lmer(grades ~ media_type_name + rev_gender_updated 
                    + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = category_subset)
lm3 <- lmerTest::lmer(grades ~ media_type_name + rev_gender_updated + category 
                    + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = category_subset)
lm4 <- lmerTest::lmer(grades ~ media_type_name + rev_gender_updated + category + rev_gender_updated:category
                    + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = category_subset)

anova(lm0, lm1, lm2, lm3, lm4)
```

```{r}
summary(lm4)

cat_plot(model = lm4, pred = rev_gender_updated, modx = category, 
         geom = 'line', interval.geom = 'linerange', x.label = 'Reviewer Gender', y.label = 'Mean Rating',
         legend.main = 'Genre', colors = palette)

ggsave('category_model_results.png', height = 3000, width = 4500, units = 'px', dpi = 'print')


```
```{r}
category_subset <- category_subset %>% 
  mutate(rev_gender_dummy = ifelse(rev_gender_updated == 'female', 0, 1))


lm4 <- lmerTest::lmer(grades ~ media_type_name + rev_gender_dummy + category + rev_gender_dummy:category
                     + (1 | media_name) + (1 | author_entity_ids_c / title_id), data = category_subset)

interact_plot(model = lm4, pred = rev_gender_dummy, modx = category, interval = T,
              x.label = 'Reviewer Gender', y.label = 'Mean Rating',legend.main = 'Genre', colors = palette)
```

